# Generated by Django 3.2 on 2024-12-04 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='restaurant.company'),
        ),
    ]
