# Generated by Django 3.2 on 2024-12-07 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_ingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='about_us_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='owner_images/')),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('facebook_link', models.URLField(blank=True, max_length=255, null=True)),
                ('instagram_link', models.URLField(blank=True, max_length=255, null=True)),
                ('linkedin_link', models.URLField(blank=True, max_length=255, null=True)),
                ('twitter_link', models.URLField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('achievements', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='restaurant.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='company_profile_images/')),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('facebook_link', models.URLField(blank=True, max_length=255, null=True)),
                ('instagram_link', models.URLField(blank=True, max_length=255, null=True)),
                ('youtube_link', models.URLField(blank=True, max_length=255, null=True)),
                ('twitter_link', models.URLField(blank=True, max_length=255, null=True)),
                ('linkedin_link', models.URLField(blank=True, max_length=255, null=True)),
                ('pinterest_link', models.URLField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('established_year', models.PositiveIntegerField(blank=True, null=True)),
                ('services_offered', models.TextField(blank=True, null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to='restaurant.company')),
            ],
        ),
    ]
