# Generated by Django 4.2.17 on 2024-12-08 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_aboutus_companyprofile_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='tiktok_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='pinterest_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='tiktok_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
